# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spectrai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spectrai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0espectrai.proto\x12\x08spectrai\"e\n\x0ePredictRequest\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x17\n\x0fsequence_length\x18\x02 \x01(\x05\x12\x11\n\tinput_dim\x18\x03 \x01(\x05\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"_\n\x0fPredictResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63tion_probs\x18\x02 \x03(\x02\x12\x12\n\nlatency_ms\x18\x03 \x01(\x02\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"\xdc\x01\n\x0cHealthStatus\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.spectrai.HealthStatus.ServingStatus\x12\x12\n\nmodel_path\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x05 \x01(\x01\"H\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x0c\n\x08STARTING\x10\x03\"\x10\n\x0eMetricsRequest\"\x92\x02\n\x0fMetricsResponse\x12\x19\n\x11predictions_total\x18\x01 \x01(\x03\x12\x18\n\x10\x63ollisions_total\x18\x02 \x01(\x03\x12\x17\n\x0fsuccesses_total\x18\x03 \x01(\x03\x12!\n\x19inference_latency_mean_ms\x18\x04 \x01(\x01\x12 \n\x18inference_latency_p50_ms\x18\x05 \x01(\x01\x12 \n\x18inference_latency_p99_ms\x18\x06 \x01(\x01\x12\x15\n\rmodel_version\x18\x07 \x01(\t\x12\x1a\n\x12\x63hannels_monitored\x18\x08 \x01(\x05\x12\x17\n\x0fprometheus_text\x18\t \x01(\t2\x95\x02\n\x08SpectrAI\x12>\n\x07Predict\x12\x18.spectrai.PredictRequest\x1a\x19.spectrai.PredictResponse\x12H\n\rPredictStream\x12\x18.spectrai.PredictRequest\x1a\x19.spectrai.PredictResponse(\x01\x30\x01\x12<\n\tGetHealth\x12\x17.spectrai.HealthRequest\x1a\x16.spectrai.HealthStatus\x12\x41\n\nGetMetrics\x12\x18.spectrai.MetricsRequest\x1a\x19.spectrai.MetricsResponseB\x1bZ\x19github.com/spectrai/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spectrai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031github.com/spectrai/proto'
  _globals['_PREDICTREQUEST']._serialized_start=28
  _globals['_PREDICTREQUEST']._serialized_end=129
  _globals['_PREDICTRESPONSE']._serialized_start=131
  _globals['_PREDICTRESPONSE']._serialized_end=226
  _globals['_HEALTHREQUEST']._serialized_start=228
  _globals['_HEALTHREQUEST']._serialized_end=243
  _globals['_HEALTHSTATUS']._serialized_start=246
  _globals['_HEALTHSTATUS']._serialized_end=466
  _globals['_HEALTHSTATUS_SERVINGSTATUS']._serialized_start=394
  _globals['_HEALTHSTATUS_SERVINGSTATUS']._serialized_end=466
  _globals['_METRICSREQUEST']._serialized_start=468
  _globals['_METRICSREQUEST']._serialized_end=484
  _globals['_METRICSRESPONSE']._serialized_start=487
  _globals['_METRICSRESPONSE']._serialized_end=761
  _globals['_SPECTRAI']._serialized_start=764
  _globals['_SPECTRAI']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
