# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from preceptualai.proto import preceptualai_pb2 as preceptualai__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in preceptualai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreceptualAIStub(object):
    """PreceptualAI inference and management service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/preceptualai.PreceptualAI/Predict',
                request_serializer=preceptualai__pb2.PredictRequest.SerializeToString,
                response_deserializer=preceptualai__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictStream = channel.stream_stream(
                '/preceptualai.PreceptualAI/PredictStream',
                request_serializer=preceptualai__pb2.PredictRequest.SerializeToString,
                response_deserializer=preceptualai__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/preceptualai.PreceptualAI/GetHealth',
                request_serializer=preceptualai__pb2.HealthRequest.SerializeToString,
                response_deserializer=preceptualai__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/preceptualai.PreceptualAI/GetMetrics',
                request_serializer=preceptualai__pb2.MetricsRequest.SerializeToString,
                response_deserializer=preceptualai__pb2.MetricsResponse.FromString,
                _registered_method=True)


class PreceptualAIServicer(object):
    """PreceptualAI inference and management service.
    """

    def Predict(self, request, context):
        """Single-shot action prediction from a spectrum observation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictStream(self, request_iterator, context):
        """Server-streaming prediction for continuous observation feeds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Health check endpoint (liveness / readiness).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Prometheus-style metrics snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreceptualAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=preceptualai__pb2.PredictRequest.FromString,
                    response_serializer=preceptualai__pb2.PredictResponse.SerializeToString,
            ),
            'PredictStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PredictStream,
                    request_deserializer=preceptualai__pb2.PredictRequest.FromString,
                    response_serializer=preceptualai__pb2.PredictResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=preceptualai__pb2.HealthRequest.FromString,
                    response_serializer=preceptualai__pb2.HealthStatus.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=preceptualai__pb2.MetricsRequest.FromString,
                    response_serializer=preceptualai__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'preceptualai.PreceptualAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('preceptualai.PreceptualAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreceptualAI(object):
    """PreceptualAI inference and management service.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preceptualai.PreceptualAI/Predict',
            preceptualai__pb2.PredictRequest.SerializeToString,
            preceptualai__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/preceptualai.PreceptualAI/PredictStream',
            preceptualai__pb2.PredictRequest.SerializeToString,
            preceptualai__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preceptualai.PreceptualAI/GetHealth',
            preceptualai__pb2.HealthRequest.SerializeToString,
            preceptualai__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preceptualai.PreceptualAI/GetMetrics',
            preceptualai__pb2.MetricsRequest.SerializeToString,
            preceptualai__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
